version: '3.3'
services:
  nginx:
    restart: always
    build:
      context: nginx
      args:
        VERSION: "${VERSION}"
        DOJO_HOST: "${DOJO_HOST}"
    ports:
    - "80:80"
    - "443:443"
    environment:
    - DH_SIZE=512
    depends_on:
    - dojo
    links:
    - dojo
  dojo:
    restart: always
    build:
      context: dojo
      args:
        VERSION: "${VERSION}"
    volumes:
      - "./static:/opt/django-DefectDojo/static"
    ports:
    - "8000:8000"
    environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=dojo
    - MYSQL_USER=dojo
    - MYSQL_PASSWORD=test123123sdasdasd221ds

    - ALLOWED_HOSTS='0.0.0.0'
    - HOST=0.0.0.0
    - LOAD_SAMPLE_DATA=False
    - GENERATE_STATIC_FILES=True
  mysql:
    restart: always
    image: mysql:5.7
    ports:
    - "3306"
    environment:
    - DOJO_MYSQL_HOST=mysql
    - DOJO_MYSQL_PORT=3306
    - MYSQL_DATABASE=dojo
    - MYSQL_USER=dojo
    - MYSQL_PASSWORD=test123123sdasdasd221ds
    - MYSQL_ROOT_PASSWORD=test123123sdasdasd221dsasdasd2dasd
    - max_allowed_packet=16M
