version: '3.3'
services:
  nginx:
    restart: always
#    image: aweaver/defectdojo-nginx:latest
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
     - DH_SIZE=512
     - DOJO_HOST=dojo
     - DOJO_PORT=8000
    depends_on:
      - dojo
    links:
      - dojo
    volumes:
      - type: volume
        source: dojo_static
        target: /opt/django-DefectDojo/static
        read_only: true
  dojo:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dojo
      - MYSQL_USER=dojo
      - MYSQL_PASSWORD=test123123sdasdasd221ds

      - ALLOWED_HOSTS='0.0.0.0'
      - LOAD_SAMPLE_DATA=False
    volumes:
      - "dojo_static:/nginx"
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      - DOJO_MYSQL_HOST=mysql
      - DOJO_MYSQL_PORT=3306
      - MYSQL_DATABASE=dojo
      - MYSQL_USER=dojo
      - MYSQL_PASSWORD=test123123sdasdasd221ds
      - MYSQL_ROOT_PASSWORD=test123123sdasdasd221dsasdasd2dasd
      - max_allowed_packet=16M
volumes:
  dojo_static: {}
